<?php
declare(strict_types=1);

namespace app\logic\system;

use app\logic\BaseLogic;
use app\model\system\SystemLinks;

class LinksLogic extends BaseLogic
{
    protected SystemLinks $model;

    protected function initialize(): void
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->model = new SystemLinks();
    }

    /**
     * @param int|string $cid
     * @return
     * @throws \Throwable
     */
    public function getLinksByCid(int|string $cid = 1)
    {
        return $this->app->cache->remember('site_links_' . $cid, function () use ($cid) {
            $where = ['cid' => $cid, 'status' => 1];
            return $this->model->where($where)->order('list', 'desc')->select()->each(function ($item) {
                if (empty($item['url']) && !empty($item['node'])) {
                    $item['url'] = hurl($item['node'], $item['params'] ?: []);
                }
                return $item;
            })->toArray();
        }, 3600);
    }
}
