<?php
declare(strict_types=1);


namespace app\logic\system;

use think\db\Query;
use happy\admin\libs\BaseLogic;
use app\model\system\SystemLinks;
use think\db\exception\DbException;
use think\db\exception\DataNotFoundException;
use think\db\exception\ModelNotFoundException;

class LinksLogic extends BaseLogic
{
    protected function initialize(): void
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
    
    /**
     * 获取分类下的链接
     * @param int|string $cid
     * @return array
     * @throws DataNotFoundException
     * @throws DbException
     * @throws ModelNotFoundException
     */
    public function getLinksByCid(int|string $cid = 1): array
    {
        $where = ['cid' => $cid, 'status' => 1];
        return SystemLinks::where($where)
            ->where(function ($query) {
                // 长期有效（is_long = 1）
                $query->whereOr('is_long', 1)
                    // 或者在有效时间范围内
                    ->whereOr(function (Query $q) {
                        $q->whereTime('start_time', '<=', time())
                            ->whereTime('end_time', '>', time());
                    });
            })
            ->order('list', 'desc')
            ->cache('systemLinksByCid_' . $cid, 3600, 'system_links_all_site')
            ->select()
            ->toArray();
    }
}
