<?php
declare(strict_types=1);

namespace app\logic\system;

use app\model\system\SystemLinks;
use mowzs\lib\BaseLogic;

class LinksLogic extends BaseLogic
{
    protected function initialize(): void
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * @param int|string $cid
     * @return
     * @throws \Throwable
     */
    public function getLinksByCid(int|string $cid = 1)
    {
        $where = ['cid' => $cid, 'status' => 1];
        return SystemLinks::where($where)->order('list', 'desc')->cache(3600)->select()->each(function ($item) {
            if (empty($item['url']) && !empty($item['node'])) {
                $item['url'] = hurl($item['node'], $item['params'] ?: []);
            }
            return $item;
        })->toArray();
    }
}
