<?php
declare(strict_types=1);

namespace app\logic\system;

use think\db\Query;
use mowzs\lib\BaseLogic;
use app\model\system\SystemNav;
use mowzs\lib\helper\DataHelper;
use think\db\exception\DbException;
use mowzs\lib\Exception\LogicException;
use think\db\exception\DataNotFoundException;
use think\db\exception\ModelNotFoundException;

class NavLogic extends BaseLogic
{
    /**
     * 缓存标签名
     * @var string
     */
    protected string $cache_tag_name = 'SiteNav';

    protected function initialize(): void
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 获取系统菜单
     * @param array $where
     * @return array
     * @throws DataNotFoundException
     * @throws DbException
     * @throws ModelNotFoundException
     */
    public function getMenuTree(array $where = ['status' => 1]): array
    {
        $data = SystemNav::where($where)->order('list', 'desc')->select()->toArray();
        return DataHelper::instance()->arrToTree($data);
    }

    /**
     * 获取菜单表单
     * @param array $where
     * @return array
     */
    public function getMenuForm(array $where = ['status' => 1]): array
    {
        return ['0' => '[顶级菜单]'] + DataHelper::instance()->transformArray(DataHelper::instance()->arrToTable(SystemNav::where($where)->order('list', 'desc')->column('title,pid,id', 'id')));
    }

    /**
     * 设置节点链接
     * @return bool|null
     * @throws LogicException
     */
    public function setNodeUrl(): ?bool
    {
        $model = new SystemNav();
        try {
            $model = $model->where(['status' => 1, 'type' => 1])->where(function (Query $query) {
                $query->whereOr('node', '!=', '')->whereNotNull('node', 'OR');
            })->field(['id', 'node', 'params']);
            foreach ($model->cursor() as $item) {
                $item['url'] = hurl($item['node'], $item['params'] ?: []);
                SystemNav::update($item);
            }
            return true;
        } catch (DataNotFoundException|ModelNotFoundException|DbException $e) {
            throw new LogicException($e->getMessage(), $e->getCode());
        }
    }

    /**
     * @param string $dir
     * @return mixed
     * @throws \Throwable
     */
    public function getNavByDir(string $dir = 'pc'): mixed
    {
        return $this->app->cache->tag($this->cache_tag_name)->remember('site_nav_' . $dir, function () use ($dir) {
            $where = ['dir' => $dir, 'status' => 1];
            $nav_data = SystemNav::where($where)->order('list', 'desc')->select()->each(function ($item) {
                if (empty($item['url']) && !empty($item['node'])) {
                    $item['url'] = hurl($item['node'], $item['params'] ?: []);
                }
                return $item;
            })->toArray();
            return DataHelper::instance()->arrToTree($nav_data, 0, 'id', 'pid', 'sub');
        }, 3600);
    }

    /**
     * 删除缓存
     * @return void
     */
    public function delNavCache(): void
    {
        $this->app->cache->clearTag([$this->cache_tag_name]);
    }
}
