<?php

namespace app\api\index;

use app\model\user\UserInfo;
use app\model\user\UserOauth;
use mowzs\lib\Controller;
use mowzs\lib\helper\CodeHelper;
use Psr\SimpleCache\InvalidArgumentException;
use think\oauth\OAuth;
use yzh52521\Jwt\JWT;

class Login extends Controller
{
    protected JWT $jwt;

    protected function initialize()
    {
        $this->jwt = new JWT();
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * @return void
     * @throws \Exception
     */
    public function wxxcx(): void
    {
        $code = $this->request->post('code');
        $wx_user_info = (new OAuth('wechat_mini', [
            'appid' => 'wx1fd453d076ddbbff',
            'secret' => 'f774038dceaf4f57720e1a15b8392418']))
            ->getUserInfo($code);
        $user_oauth = new UserOauth();
        $uid = $user_oauth->where(['type' => 'wxxcx', 'openid' => $wx_user_info['openid']])->value('uid');
        if (!empty($uid)) {  //包含uid 则说明已创建用户
            $user = (new \app\model\user\UserInfo)->findOrEmpty($uid);
        } else {//不包含则自动新建用户
            $user = new UserInfo();
            $user->username = 'wxxcx' . CodeHelper::randomString(4) . CodeHelper::randomString(4);
            $user->password = password_hash(md5(CodeHelper::randomString(8)), PASSWORD_DEFAULT);
            $user->nickname = $wx_user_info['nickname'] ?: '微信用户' . CodeHelper::randomString(6);
            $user->avatar = '';
            $user->last_ip = $this->request->ip();
            $user->last_time = time();
            $user->mobile = null;
            $user->save();
            UserOauth::create(['uid' => $user->id, 'type' => 'wxxcx', 'openid' => $wx_user_info['openid'], 'unionid' => $wx_user_info['unionid']]);
        }
        try {
            $token = $this->jwt->getToken('default', $user->toArray());
            $data = [
                'token' => $token->toString(),
                'expires_in' => $this->jwt->getTTL($token->toString()),
            ];
            $this->json($data);
        } catch (InvalidArgumentException $e) {
            $this->json(['msg' => $e->getMessage()], 500);
        }
    }
}
