<?php

namespace app\common\controllers;

use yzh52521\Jwt\Middleware\JWTAuthDefaultSceneMiddleware;

class BaseApiAuth extends BaseApi
{
    protected function initialize(): void
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        //注册请求响应过滤中间件
        $this->app->middleware->add(JWTAuthDefaultSceneMiddleware::class, 'route');
    }
}
