<?php
declare (strict_types=1);

namespace app\common\controllers;

class BaseApi extends Base
{
    protected function initialize(): void
    {
        $this->app->event->trigger('ApiControllerInit');
        parent::initialize(); // TODO: Change the autogenerated stub
    }
}
