<?php
declare (strict_types=1);

namespace app\common\controllers;

use think\App;

class BaseHome extends Base
{

    public function __construct(App $app)
    {
        parent::__construct($app);
        $this->app->event->trigger('HomeControllerInit');
    }

    /**
     * 初始化设置
     * @return void
     */
    protected function initialize(): void
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        try {
            if ($this->app->config->get('happy.installed', false) && (int)sys_config('is_open_site') === 0) {
                $this->closeSite('网站暂未开启!敬请期待');
            }
        } catch (\Exception $e) {
            $this->app->log->error($e->getMessage(), $e->getTrace());
        }
    }
}
