<?php
declare (strict_types=1);

namespace app\common\controllers;

use app\common\middleware\api\JWTAuthDefaultSceneMiddleware;
use mowzs\lib\Controller;

class BaseApi extends Controller
{
    protected function initialize(): void
    {
        $this->app->middleware->add(JWTAuthDefaultSceneMiddleware::class);
        $this->app->event->trigger('ApiControllerInit');
        parent::initialize(); // TODO: Change the autogenerated stub
    }
}
