<?php
declare (strict_types=1);


namespace app\common\controllers;

use think\App;
use think\facade\View;

class BaseHome extends Base
{
    
    public function __construct(App $app)
    {
        parent::__construct($app);
        $this->app->event->trigger('HomeControllerInit');
    }
    
    /**
     * 初始化设置
     * @return void
     * @throws \Throwable
     */
    protected function initialize(): void
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        try {
            if ($this->app->config->get('happy.installed', false) && (int)sys_config('is_open_site') === 0) {
                $this->closeSite('网站暂未开启!敬请期待');
            }
        } catch (\Exception $e) {
            $this->app->log->error($e->getMessage(), $e->getTrace());
        }
    }
    
    protected function fetch(string $template = '', array $vars = []): string
    {
        if ($this->request->isAjax()) {
            $baseTemplate = empty($template) ? $this->request->action(true) : $template;
            $ajaxTemplate = $baseTemplate . '_ajax';
            
            if (View::exists($ajaxTemplate)) {
                return parent::fetch($ajaxTemplate, $vars);
            }
        }
        
        return parent::fetch($template, $vars);
    }
}
