<?php
declare (strict_types=1);

namespace app\common\controllers;

use think\db\exception\DataNotFoundException;
use think\db\exception\DbException;
use think\db\exception\ModelNotFoundException;

class BaseHome extends Base
{
    /**
     * 初始化设置
     * @return void
     */
    protected function initialize(): void
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        try {
            if (sys_config('is_open_site') != 1) {
                $this->closeSite('网站暂未开启!敬请期待');
            }
        } catch (DataNotFoundException|ModelNotFoundException|DbException $e) {
            $this->app->log->error('is_open_site 获取失败:' . $e->getMessage());
        }
    }
}
