<?php
declare (strict_types=1);

namespace app\common\controllers;

use happy\admin\libs\Controller;
use app\logic\system\ConfigLogic;
use happy\admin\libs\helper\UserHelper;
use app\common\traits\system\ViewTheme;

class Base extends Controller
{
    use ViewTheme;
    
    /**
     * 用户信息
     * @var array|false
     */
    protected array|false $user;
    /**
     * 网站配置信息
     * @var mixed
     */
    protected mixed $web_config;
    /**
     * 系统模块
     * @var string
     */
    protected string $sys_module;
    
    protected function initialize(): void
    {
        $this->user = UserHelper::instance()->getUserInfo();
        if ($this->app->config->get('happy.installed', false)) {
            $this->web_config = ConfigLogic::instance()->getConfigValue();
        } else {
            $this->redirect(urls('install/index/index'));
        }
        $this->setView();
        $this->sys_module = $this->request->layer(true);
        parent::initialize(); // TODO: Change the autogenerated stub
    }

}
