<?php
declare (strict_types=1);

namespace app\common\controllers;

use app\common\middleware\api\JWTAuthDefaultSceneMiddleware;
use mowzs\lib\Controller;
use yzh52521\Jwt\Util\JWTUtil;

class BaseApi extends Controller
{
    protected int $uid;

    protected function initialize(): void
    {
        $this->app->middleware->add(JWTAuthDefaultSceneMiddleware::class);
        $this->app->event->trigger('ApiControllerInit');
        $claims = JWTUtil::getParserData($this->request);
        $this->uid = $claims['id'];
        if (!$this->uid) {
            $this->json([], 401, '请登录！');
        }
        parent::initialize(); // TODO: Change the autogenerated stub
    }

}
