<?php
declare(strict_types=1);

namespace app\logic\user;

use app\logic\BaseLogic;
use app\model\user\UserInfo;

class UserLogic extends BaseLogic
{
    /**
     * 用户信息模型
     * @var UserInfo
     */
    protected UserInfo $userInfoModel;

    /**
     * @return void
     */
    protected function initialize(): void
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->userInfoModel = new  UserInfo();
    }

    public function getUserInfoById($uid = ''): array
    {
        if (empty($uid)) {
            return [];
        }
        return $this->userInfoModel->with(['usergroup'])->findOrEmpty($uid)->toArray();
    }
}
